# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c612d93004d0256d8f0b98c12fa94a43c443cf865769b0251b64c081ce1e96a83ecd456d20a5b9c06f0b69de3428d09d3c70be712195c9857180261fd5adfc1

test:
  secret_key_base: 52090b21b027dfe59c5ce0fa7b34745858049c5645f9409d1942d05eba60f3765c0bb81a9171f299043300e8dd0be0c04b296a7c640579fc181a683f8cfb2f17

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
