# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
User.create( username: "chris", password: "superman")
User.create( username: "demo", password: "password")
User.create( username: "test", password: "password")
User.create( username: "test1", password: "password")
User.create( username: "test2", password: "password")
User.create( username: "test3", password: "password")
User.create( username: "test4", password: "password")
User.create( username: "test5", password: "password")


Post.create( title: "Whatcha doin?", url: "http://i.imgur.com/kijXP0K.jpg", sub: "aww", user_id: 3)
Post.create( title: "angry cat", url: "http://i.imgur.com/Uek5LUD.jpg", sub: "aww", user_id: 1)
Post.create( title: "conviction cat", url: "http://i.imgur.com/SpCbHBI.jpg", sub: "aww", user_id: 1)
Post.create( title: "waterfall", url: "http://ppcdn.500px.org/71174873/a2a4a29222991f2e66e77f77e9958f90229ae688/2048.jpg", user_id: 1)
Post.create( title: "aww cat", url: "http://i.imgur.com/evurnyI.jpg", sub: "aww", user_id: 1)
Post.create( title: "pizza fries", url: "http://i.imgur.com/5ywsGIw.jpg", user_id: 1)
Post.create( title: "kangaroo", url: "http://i.imgur.com/cQ5E4ID.jpg", sub: "aww", user_id: 2)
Post.create( title: "ESPN", url: "http://www.espn.com", body: "Sport News Website", user_id: 2)
Post.create( title: "google", url: "http://www.google.com", body: "search engine", user_id: 2)
Post.create( title: "Low pressure condensation", url: "http://i.imgur.com/1vLQ1vj.jpg", user_id: 5)
Post.create( title: "C-17 At Night", url: "http://i.imgur.com/z4tn4pL.jpg", user_id: 1)
Post.create( title: "Cat hat", sub: "aww", url: "http://imgur.com/AcJgWRM.gif", user_id: 1)
Post.create( title: "Shanghai view", sub: "pics", url: "http://i.imgur.com/VgCiEQj.jpg", user_id: 1)
Post.create( title: "NASA solar flare", sub: "science", url: "http://i.imgur.com/fNe34M1.jpg", user_id: 1)
Post.create( title: "fish photo bomb", sub: "funny", url: "http://scout.cheatsheet.me/wp-content/uploads/2014/04/best_photobombs_22.jpg", user_id: 1)
Post.create( title: "Game Over Mario", sub: "gaming", url: "http://i.imgur.com/z1Gu22E.gif", user_id: 1)
Post.create( title: "I just wanna see", sub: "aww", url: "http://i.imgur.com/S0gc5mA.gif", user_id: 1)
Post.create( title: "I love this stuff", sub: "aww", url: "http://i.imgur.com/BwNGyfV.jpg", user_id: 1)
Post.create( title: "Lemur Selfie", sub: "aww", url: "http://i.imgur.com/JPidICi.jpg", user_id: 1)
Post.create( title: "Cuteness overload", sub: "aww", url: "http://1-ps.googleusercontent.com/h/www.catgifpage.com/gifs/232.gif.pagespeed.ce.XX3Zi5OI3e.gif", user_id: 1)
Post.create( title: "Some say he is still standing", sub: "aww", url: "http://i.imgur.com/vBhQHwt.jpg", user_id: 1)
#Post.create( title: "", url: "", user_id: 1)

Vote.create( user_id: 1, post_id: 1, value: 1)
Vote.create( user_id: 2, post_id: 1, value: 1)
Vote.create( user_id: 1, post_id: 2, value: -1)
Vote.create( user_id: 2, post_id: 2, value: 1)
Vote.create( user_id: 1, post_id: 3, value: 1)
Vote.create( user_id: 3, post_id: 1, value: 1)
Vote.create( user_id: 4, post_id: 1, value: 1)
Vote.create( user_id: 5, post_id: 1, value: 1)

Comment.create( user_id: 1, body: "Parent Comment", post_id: 1)
Comment.create( user_id: 1, parent_id: 1, body: "Child Comment", post_id: 1)
Comment.create( user_id: 1, parent_id: 2, body: "Child Child Comment", post_id: 1)
Comment.create( user_id: 1, body: "Recursive Nested Comments!", post_id: 1)
Comment.create( user_id: 1, parent_id: 4, body: "[comment deleted by chris]", post_id: 1)

CommentVote.create( user_id: 1, comment_id: 1, value: 1 )
CommentVote.create( user_id: 2, comment_id: 1, value: 1 )
CommentVote.create( user_id: 3, comment_id: 1, value: 1 )
CommentVote.create( user_id: 4, comment_id: 2, value: 1 )
CommentVote.create( user_id: 5, comment_id: 2, value: 1 )
CommentVote.create( user_id: 6, comment_id: 3, value: 1 )
CommentVote.create( user_id: 7, comment_id: 5, value: -1 )